### ISSUE TITLE
Fix App bar title Change

### ISSUE THREAD

**Issue by yashLadha** [Hatsphere/Android-User#4]
The app bar title is not displaying correctly

**Comment by Pritom14** [comment]
Can I work on this?

**Comment by yashLadha** [comment]
Sorry @Pritom14 but it is aimed for my team mate.

**Comment by yogeshAgarwal** [comment]
Please elaborate @yashLadha

**Comment by yashLadha** [comment]
I had made ammends.

**Comment by yashLadha** [comment]
Implemented
